source("https://bioconductor.org/biocLite.R")

list.of.packages <- c("ggplot2", "XML", "mgcv", "reshape2", "grid", "gridExtra", "gplots","pheatmap","RColorBrewer", 
                      "VennDiagram", "gdata", "e1071", "genefu", "xtable", "data.table", "snowfall", "utils",
                      "Hmisc", "WriteXLS", "qpcR", "rgl", "devtools", "ggplot2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos='http://cran.utstat.utoronto.ca/')

biocLite(pkgs = c("Biobase", "survcomp", "piano", "PharmacoGx", "biomaRt", "preprocessCore"))

library(mgcv)
library(reshape2)
library(gridExtra)
library(grid)
library(gplots)
library(RColorBrewer)
library(pheatmap)
library(VennDiagram)
library(gdata)
library(e1071)
library(genefu)
library(xtable)
library(biomaRt)
library(devtools)
library(preprocessCore)
library(rgl)
library(qpcR)
library(data.table)
library(snowfall)
library(utils)
library(Hmisc)
library(WriteXLS)
library(Biobase)
library(piano)
library(PharmacoGx)
library(survcomp)
library(ggplot2)